[public]
# Public jump VM
# public-web-vm ansible_host=20.1.2.3 ansible_user=azureuser ansible_password=Password1234! ansible_ssh_common_args='-o StrictHostKeyChecking=no'

[private]
# Private VM reachable through the public VM as a jump host
# private-app-vm ansible_host=10.0.3.4 ansible_user=azureuser ansible_password=Password1234! ansible_ssh_common_args='-o StrictHostKeyChecking=no -o ProxyCommand="ssh -W %h:%p -o StrictHostKeyChecking=no azureuser@20.1.2.3"'
